# Generated by Django 4.2 on 2026-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_verified_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='barangay',
            field=models.CharField(choices=[('Cabaroan', 'Cabaroan (5.6 km from DMMMSU NLUC)'), ('Say-oan', 'Say-oan (4.5 km from DMMMSU NLUC)'), ('Salincob', 'Salincob (3.2 km from DMMMSU NLUC)'), ('Casiaman', 'Casiaman (1.5 km from DMMMSU NLUC)'), ('Sapilang', 'Sapilang (walking distance from campus)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
