# Generated by Django 4.2 on 2026-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_boardinghouse_barangay_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='barangay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
