# Generated by Django 4.2.15 on 2026-08-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='distance_from_campus',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Distance from DMMMSU NLUC campus'),
        ),
    ]
