# Generated by Django 4.2 on 2026-08-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listing_approval_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified_status',
        ),
    ]
