# Generated by Django 4.2 on 2026-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_verified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='gender_allowed',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('both', 'Both (Male & Female)')], default='both', max_length=10, verbose_name='Gender allowed'),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_images/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (₱ per month)'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='description',
            field=models.TextField(blank=True, help_text='Optional. Up to 500 words.'),
        ),
        migrations.AlterField(
            model_name='boardinghouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the boarding house'),
        ),
    ]
