# Generated by Django 6.0.8 on 2026-08-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_boardinghouse_price_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='landlord_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment or Abuse'), ('scam', 'Scam or Fraud'), ('fake_listing', 'Fake Listing'), ('inappropriate', 'Inappropriate Behavior'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
