# Generated by Django 6.0.8 on 2026-08-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_landlord_id_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program_custom',
            field=models.CharField(blank=True, help_text='Free text for the course name or grade level when Program is "Other" or "K-12".', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, choices=[('CE', 'College of Education'), ('CA', 'College of Agriculture'), ('CAS', 'College of Arts and Sciences'), ('CVM', 'College of Veterinary Medicine'), ('CAFF', 'College of Agroforestry & Forestry'), ('IABM', 'Institute of Agribusiness Management'), ('CIS', 'College of Information Systems'), ('IES', 'Institute of Environmental Studies'), ('IABE', 'Institute of Agricultural & Biosystems Engineering'), ('K12', 'K-12 / Senior High School'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
