# Generated by Django 6.0.8 on 2026-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_other_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program_custom',
            field=models.CharField(blank=True, help_text='Free text for the grade level when Program is "K-12".', max_length=100),
        ),
    ]
