# Generated by Django 6.0.8 on 2026-08-24 08:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seed_bacnotan_barangays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boarding_images/', validators=[core.models.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(upload_to='room_photos/', validators=[core.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[core.models.validate_image_size]),
        ),
    ]
