# Generated by Django 6.0.8 on 2026-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_boardinghouse_image_alter_roomphoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_inquiries',
            field=models.DateTimeField(blank=True, help_text='When the landlord last opened their inquiry list; newer inquiries show a NEW chip.', null=True),
        ),
    ]
