# Generated by Django 6.0.8 on 2026-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_last_seen_inquiries'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='last_viewed_by_landlord',
            field=models.DateTimeField(blank=True, help_text='When the landlord last opened this inquiry thread.', null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
